[2020-11-25 17:03:02,034: INFO/MainProcess] Connected to redis://localhost:6379//
[2020-11-25 17:03:03,909: INFO/MainProcess] mingle: searching for neighbors
[2020-11-25 17:03:08,941: INFO/MainProcess] mingle: all alone
[2020-11-25 17:03:10,950: WARNING/MainProcess] /usr/local/lib/python3.7/dist-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  leak, never use this setting in production environments!''')
[2020-11-25 17:03:10,952: INFO/MainProcess] celery@worker1 ready.
[2020-11-25 17:13:48,197: INFO/MainProcess] Received task: tempsens.tasks.getInfo[c1a4a37e-9400-4091-8eef-1771aec689f7]  
[2020-11-25 17:13:48,851: INFO/ForkPoolWorker-1] Task tempsens.tasks.getInfo[c1a4a37e-9400-4091-8eef-1771aec689f7] succeeded in 0.6310208469999452s: {'temp': 24.0, 'hum': 56.0}
[2020-11-25 17:23:48,644: INFO/MainProcess] Received task: tempsens.tasks.powerOnLed[42d5e115-5c22-46b9-8d72-33c648783412]  
[2020-11-25 17:23:48,701: INFO/ForkPoolWorker-1] Task tempsens.tasks.powerOnLed[42d5e115-5c22-46b9-8d72-33c648783412] succeeded in 0.03427104200000031s: None
[2020-11-25 17:43:39,586: INFO/MainProcess] Received task: tempsens.tasks.powerOnLed[ca969b25-95c4-470b-b974-6e016466ca66]  
[2020-11-25 17:43:39,615: INFO/ForkPoolWorker-1] Task tempsens.tasks.powerOnLed[ca969b25-95c4-470b-b974-6e016466ca66] succeeded in 0.01993288899984691s: None
[2020-11-25 17:43:43,421: INFO/MainProcess] Received task: tempsens.tasks.getInfo[15abeb4c-91ea-42e8-930e-b812271d3dca]  
[2020-11-25 17:43:43,985: INFO/ForkPoolWorker-1] Task tempsens.tasks.getInfo[15abeb4c-91ea-42e8-930e-b812271d3dca] succeeded in 0.5432519699998011s: {'temp': 24.0, 'hum': 53.0}
[2020-11-25 17:52:02,363: INFO/MainProcess] Received task: tempsens.tasks.getInfo[c00eaae5-a422-4325-943d-52fb92334673]  
[2020-11-25 17:52:05,472: INFO/ForkPoolWorker-1] Task tempsens.tasks.getInfo[c00eaae5-a422-4325-943d-52fb92334673] succeeded in 3.090354391999881s: {'temp': 24.0, 'hum': 53.0}
[2020-11-25 17:52:08,491: INFO/MainProcess] Received task: tempsens.tasks.getInfo[885e68ad-770b-41fc-930d-b896d4d79e77]  
[2020-11-25 17:52:09,067: INFO/ForkPoolWorker-1] Task tempsens.tasks.getInfo[885e68ad-770b-41fc-930d-b896d4d79e77] succeeded in 0.5557430129997556s: {'temp': 24.0, 'hum': 53.0}
[2020-11-26 16:56:12,577: INFO/MainProcess] Received task: tempsens.tasks.getInfo[d484a3c5-8450-41f2-8ce7-cedcf798b8c1]  
[2020-11-26 16:56:13,163: INFO/ForkPoolWorker-1] Task tempsens.tasks.getInfo[d484a3c5-8450-41f2-8ce7-cedcf798b8c1] succeeded in 0.551729038998019s: {'temp': 24.0, 'hum': 53.0}
[2020-11-26 16:56:26,171: INFO/MainProcess] Received task: tempsens.tasks.getInfo[298e8bc4-8caf-429d-8754-ca071907a835]  
[2020-11-26 16:56:34,351: INFO/ForkPoolWorker-1] Task tempsens.tasks.getInfo[298e8bc4-8caf-429d-8754-ca071907a835] succeeded in 8.155352832007338s: {'temp': 24.0, 'hum': 52.0}
[2020-11-26 18:08:51,317: INFO/MainProcess] Received task: tempsens.tasks.getInfo[3e9cc545-5377-49ad-987a-7e22f1f41e55]  
[2020-11-26 18:08:51,874: INFO/ForkPoolWorker-1] Task tempsens.tasks.getInfo[3e9cc545-5377-49ad-987a-7e22f1f41e55] succeeded in 0.5421046029950958s: {'temp': 24.0, 'hum': 52.0}
[2020-11-26 18:08:57,468: INFO/MainProcess] Received task: tempsens.tasks.getInfo[f39b104c-d17f-441d-b64c-5153681bc86f]  
[2020-11-26 18:08:58,054: INFO/ForkPoolWorker-1] Task tempsens.tasks.getInfo[f39b104c-d17f-441d-b64c-5153681bc86f] succeeded in 0.5636076259979745s: {'temp': 24.0, 'hum': 53.0}
[2020-11-26 18:13:25,751: INFO/MainProcess] Received task: tempsens.tasks.getInfo[e99c2d07-0282-4def-9a0f-502c35cda006]  
[2020-11-26 18:13:26,303: INFO/ForkPoolWorker-1] Task tempsens.tasks.getInfo[e99c2d07-0282-4def-9a0f-502c35cda006] succeeded in 0.5421235730027547s: {'temp': 24.0, 'hum': 53.0}
[2020-11-26 18:17:32,372: INFO/MainProcess] Received task: tempsens.tasks.powerOnLed[76a67163-5ddc-4d4c-96b0-97a021aee637]  
[2020-11-26 18:17:32,420: INFO/ForkPoolWorker-1] Task tempsens.tasks.powerOnLed[76a67163-5ddc-4d4c-96b0-97a021aee637] succeeded in 0.03205104000517167s: None
[2020-11-26 18:25:24,704: INFO/MainProcess] Received task: tempsens.tasks.getInfo[c5dee63e-1b6d-4ed0-8442-1a3ceb62d5b4]  
[2020-11-26 18:25:25,281: INFO/ForkPoolWorker-1] Task tempsens.tasks.getInfo[c5dee63e-1b6d-4ed0-8442-1a3ceb62d5b4] succeeded in 0.5599296869913815s: {'temp': 24.0, 'hum': 53.0}
[2020-11-26 18:25:37,218: INFO/MainProcess] Received task: tempsens.tasks.getInfo[b6ba460b-fb42-4b0c-a2b5-962c7c2483db]  
[2020-11-26 18:25:37,782: INFO/ForkPoolWorker-1] Task tempsens.tasks.getInfo[b6ba460b-fb42-4b0c-a2b5-962c7c2483db] succeeded in 0.5420060839969665s: {'temp': 24.0, 'hum': 53.0}
[2020-11-26 18:26:13,070: INFO/MainProcess] Received task: tempsens.tasks.powerOffLed[a89dd04a-6dce-4f4a-a2f8-715ca7e78205]  
[2020-11-26 18:26:13,113: INFO/ForkPoolWorker-1] Task tempsens.tasks.powerOffLed[a89dd04a-6dce-4f4a-a2f8-715ca7e78205] succeeded in 0.021226704004220665s: None
/home/pi/rpi_temp/django_app/tempsens/tasks.py:11: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(led, GPIO.OUT)
[2020-11-26 18:32:59,766: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2020-11-26 18:33:01,802: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2020-11-26 18:33:05,835: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2020-11-26 18:33:11,878: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2020-11-26 18:33:19,945: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2020-11-26 18:33:30,001: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 12.00 seconds... (6/100)

[2020-11-26 18:33:42,065: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 14.00 seconds... (7/100)

